#India batting 
India_batting <- list(length(11))
India_batting[[1]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=RG+Sharma&role=all&format=all&groupby=year",3)
India_batting[[2]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=HH+Pandya&role=all&format=all&groupby=year",3)
India_batting[[3]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Shubman+Gill&role=all&format=all&groupby=year",3)
India_batting[[4]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=V+Kohli&role=all&format=all&groupby=year",3)
India_batting[[5]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=SS+Iyer&role=all&format=all&groupby=year",3)
India_batting[[6]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=KL+Rahul&role=all&format=all&groupby=year",3)
India_batting[[7]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=RA+Jadeja&role=all&format=all&groupby=year",3)
India_batting[[8]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=SN+Thakur&role=all&format=all&groupby=year",3)
India_batting[[9]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=JJ+Bumrah&role=all&format=all&groupby=year",3)
India_batting[[10]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Kuldeep+Yadav&role=all&format=all&groupby=year",3)
India_batting[[11]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Mohammed+Shami&role=all&format=all&groupby=year",3)

# Pakistan batting
Pakistan_batting <- list(length(11))
Pakistan_batting[[1]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Babar+Azam&role=all&format=all&groupby=year",3)
Pakistan_batting[[2]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Shadab+Khan&role=all&format=all&groupby=year",3)
Pakistan_batting[[3]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Abdullah+Shafique&role=all&format=all&groupby=year",3)
Pakistan_batting[[4]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Hasan+Ali&role=all&format=all&groupby=year",3)
Pakistan_batting[[5]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Haris+Rauf&role=all&format=all&groupby=year",3)
Pakistan_batting[[6]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Fakhar+Zaman&role=all&format=all&groupby=year",3)
Pakistan_batting[[7]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Imam-ul-Haq&role=all&format=all&groupby=year",3)
Pakistan_batting[[8]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Iftikhar+Ahmed&role=all&format=all&groupby=year",3)
Pakistan_batting[[9]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Mohammad+Nawaz%283%29&role=all&format=all&groupby=year",3)
Pakistan_batting[[10]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Mohammad+Wasim%281%29&role=all&format=all&groupby=year",3)
Pakistan_batting[[11]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Mohammad+Rizwan&role=all&format=all&groupby=year",3)

# Australia batting
Australia_batting <- list(length(11))
Australia_batting[[1]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=PJ+Cummins&role=all&format=all&groupby=year",3)
Australia_batting[[2]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=SPD+Smith&role=all&format=all&groupby=year",3)
Australia_batting[[3]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=AT+Carey&role=all&format=all&groupby=year",3)
Australia_batting[[4]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=JP+Inglis&role=all&format=all&groupby=year",1)
Australia_batting[[5]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=SA+Abbott&role=all&format=all&groupby=year",1)
Australia_batting[[6]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=M+Labuschagne&role=all&format=all&groupby=year",3)
Australia_batting[[7]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=C+Green&role=all&format=all&groupby=year",3)
Australia_batting[[8]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=JR+Hazlewood&role=all&format=all&groupby=year",3)
Australia_batting[[9]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=TM+Head&role=all&format=all&groupby=year",3)
Australia_batting[[10]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MR+Marsh&role=all&format=all&groupby=year",3)
Australia_batting[[11]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=GJ+Maxwell&role=all&format=all&groupby=year",3)

# England batting
England_batting <- list(length(11))
England_batting[[1]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=JC+Buttler&role=all&format=all&groupby=year",3)
England_batting[[2]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MM+Ali&role=all&format=all&groupby=year",3)
England_batting[[3]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=AAP+Atkinson&role=all&format=all&groupby=year",1)
England_batting[[4]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=JM+Bairstow&role=all&format=all&groupby=year"3)
England_batting[[5]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=SM+Curran&role=all&format=all&groupby=year",3)
England_batting[[6]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=LS+Livingstone&role=all&format=all&groupby=year",3)
England_batting[[7]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=DJ+Malan&role=all&format=all&groupby=year",3)
England_batting[[8]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=AU+Rashid&role=all&format=all&groupby=year",3)
England_batting[[9]] <-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=JE+Root&role=all&format=all&groupby=year",3)
England_batting[[10]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=HC+Brook&role=all&format=all&groupby=year",3)
England_batting[[11]]<-  Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=BA+Stokes&role=all&format=all&groupby=year",3)

# New Zealand batting
New_Zealand_batting <- list(length(11))
New_Zealand_batting[[1]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=KS+Williamson&role=all&format=all&groupby=year",3)
New_Zealand_batting[[2]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=TA+Boult&role=all&format=all&groupby=year",3)
New_Zealand_batting[[3]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MS+Chapman&role=all&format=all&groupby=year",1)
New_Zealand_batting[[4]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=DP+Conway&role=all&format=all&groupby=year",3)
New_Zealand_batting[[5]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=LH+Ferguson&role=all&format=all&groupby=year",3)
New_Zealand_batting[[6]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MJ+Henry&role=all&format=all&groupby=year",3)
New_Zealand_batting[[7]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=TWM+Latham&role=all&format=all&groupby=year",3)
New_Zealand_batting[[8]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=DJ+Mitchell&role=all&format=all&groupby=year",3)
New_Zealand_batting[[9]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=JDS+Neesham&role=all&format=all&groupby=year",3)
New_Zealand_batting[[10]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=GD+Phillips&role=all&format=all&groupby=year",3)
New_Zealand_batting[[11]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=R+Ravindra&role=all&format=all&groupby=year",3)

# South Africa batting
South_Africa_batting <- list(length(11))
South_Africa_batting[[1]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=T+Bavuma&role=all&format=all&groupby=year",3)
South_Africa_batting[[2]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=G+Coetzee&role=all&format=all&groupby=year",3)
South_Africa_batting[[3]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Q+de+Kock&role=all&format=all&groupby=year",3)
South_Africa_batting[[4]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=RR+Hendricks&role=all&format=all&groupby=year",1)
South_Africa_batting[[5]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=M+Jansen&role=all&format=all&groupby=year",3)
South_Africa_batting[[6]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=H+Klaasen&role=all&format=all&groupby=year",3)
South_Africa_batting[[7]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=AL+Phehlukwayo&role=all&format=all&groupby=year",3)
South_Africa_batting[[8]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=KA+Maharaj&role=all&format=all&groupby=year",3)
South_Africa_batting[[9]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=AK+Markram&role=all&format=all&groupby=year",3)
South_Africa_batting[[10]]<-Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=DA+Miller&role=all&format=all&groupby=year",3)
South_Africa_batting[[11]]<-Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=L+Ngidi&role=all&format=all&groupby=year",3)
    
# Sri lanka batting
Sri_Lanka_batting <- list(length(11))
Sri_Lanka_batting[[1]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MD+Shanaka&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[2]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=BKG+Mendis&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[3]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=P+Nissanka&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[4]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MDKJ+Perera&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[5]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=FDM+Karunaratne&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[6]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=KIC+Asalanka&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[7]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=DM+de+Silva&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[8]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MADI+Hemantha&role=all&format=all&groupby=year",1)
Sri_Lanka_batting[[9]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=S+Samarawickrama&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[10]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=DN+Wellalage&role=all&format=all&groupby=year",3)
Sri_Lanka_batting[[11]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=CAK+Rajitha&role=all&format=all&groupby=year",3)
  
# Afghanistan batting
Afghanistan_batting <- list(length(11))
Afghanistan_batting[[1]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Hashmatullah+Shahidi&role=all&format=all&groupby=year",3)
Afghanistan_batting[[2]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Ibrahim+Zadran&role=all&format=all&groupby=year",3)
Afghanistan_batting[[3]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Rahmanullah+Gurbaz&role=all&format=all&groupby=year",1)
Afghanistan_batting[[4]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Rahmat+Shah&role=all&format=all&groupby=year",3)
Afghanistan_batting[[5]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Najibullah+Zadran&role=all&format=all&groupby=year",1)
Afghanistan_batting[[6]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Mohammad+Nabi&role=all&format=all&groupby=year",3)
Afghanistan_batting[[7]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Ikram+Alikhil&role=all&format=all&groupby=year",3)
Afghanistan_batting[[8]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Azmatullah+Omarzai&role=all&format=all&groupby=year",1)
Afghanistan_batting[[9]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Rashid+Khan&role=all&format=all&groupby=year",3)
Afghanistan_batting[[10]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Abdul+Rahman&role=all&format=all&groupby=year",1)
Afghanistan_batting[[11]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Noor+Ahmad&role=all&format=all&groupby=year",1)
  
# Netherlands batting
Netherlands_batting <- list(length(11))
Netherlands_batting[[1]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=SA+Edwards&role=all&format=all&groupby=year",1)
Netherlands_batting[[2]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=MP+O%27Dowd&role=all&format=all&groupby=year",1)
Netherlands_batting[[3]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=BFW+de+Leede&role=all&format=all&groupby=year",1)
Netherlands_batting[[4]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=Vikramjit+Singh&role=all&format=all&groupby=year",1)
Netherlands_batting[[5]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=AT+Nidamanuru&role=all&format=all&groupby=year",1)
Netherlands_batting[[6]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=PA+van+Meekeren&role=all&format=all&groupby=year",1)
Netherlands_batting[[7]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=CN+Ackermann&role=all&format=all&groupby=year",1)
Netherlands_batting[[8]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=RE+van+der+Merwe&role=all&format=all&groupby=year",1)
Netherlands_batting[[9]] <- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=LV+van+Beek&role=all&format=all&groupby=year",1)
Netherlands_batting[[10]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=A+Dutt&role=all&format=all&groupby=year",1)
Netherlands_batting[[11]]<- Scrap_Bating_data(link = "http://www.cricmetric.com/playerstats.py?player=R+Klein&role=all&format=all&groupby=year",1)